# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node version to 14.17.6
      uses: actions/setup-node@v2
      with:
        node-version: '14.17.6'
    - name: Install Dependencies
      run: yarn install
    
    # Run lint
    - name: Run tslint formatting
      run: yarn lint
      
    # Run unit test
    - name: Run jest unit tests
      run: yarn test:ci

    - name: Build package
      run: yarn build
